services:
  digitalisation_toolkit-nginx:
    container_name: digitalisation_toolkit-nginx
    image: nginx:1.27.2-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Singapore
    networks:
      - digitalisation_toolkit-network
    restart: unless-stopped

  digitalisation_toolkit-frontend:
    container_name: digitalisation_toolkit-frontend
    restart: unless-stopped
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Timezone configuration
      - TZ=Asia/Singapore
      # LLM API URLs (Replace with your actual API endpoints)
      - TRANSLATION_API_URL=${TRANSLATION_API_URL:-http://webworkdgx/vllm_sealion}
      - GENERAL_API_URL=${GENERAL_API_URL:-http://webworkdgx/vllm_qwen2_5}
      # API Tokens (Set these in your environment or .env file)
      - TRANSLATION_API_TOKEN=${TRANSLATION_API_TOKEN}
      - GENERAL_API_TOKEN=${GENERAL_API_TOKEN}
    networks:
      - digitalisation_toolkit-network
    depends_on:
      - digitalisation_toolkit-nginx

  digitalisation_toolkit-backend:
    container_name: digitalisation_toolkit-backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - digitalisation_toolkit-network
    restart: unless-stopped
    depends_on:
      - digitalisation_toolkit-nginx
    runtime: nvidia
    environment:
      # Timezone configuration
      - TZ=Asia/Singapore
      # NVIDIA GPU configuration
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

networks:
  digitalisation_toolkit-network:
    name: digitalisation_toolkit-network
    driver: bridge
